# Site settings
title: Screen Recorder
description: A modern, browser-based tool for Screen Recording
url: https://dylansallred.github.io

# Theme settings
theme: jekyll-theme-minimal
google_analytics: # Add your Google Analytics ID here if needed

# Build settings
markdown: kramdown 